import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import LoginControl from './components/07_conditionalRendering'
import NumberList from './components/08_listAndKeys'
import {NameForm, EssayForm, FlavorForm, Reservation} from './components/09-forms'
import Calculator from './components/10-liftingStateUp'
import FilterableProductTable from './components/12-thinkingInReact'

/*
<button onClick={(e) => this.deleteRow(id,e)}> Delete Row </button>
<button onClick={this.deleteRow.bind(this, id)}> Delete Row </button>      
*/  

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1> Testing Main Concepts </h1>

          <LoginControl/>
          <NumberList numbers={[1,2,3,4]}/>
          
          <NameForm/>
          <br/>
          <EssayForm/>
          <br/>
          <FlavorForm/>
          <hr/>
          <Reservation/> 
          <hr/>
    
          <Calculator/>

          <FilterableProductTable products={PRODUCTS}/> 
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

const PRODUCTS = [
  {category: 'Sporting Goods', price: '$49.99', stocked: true, name: 'Football'},
  {category: 'Sporting Goods', price: '$9.99', stocked: true, name: 'Baseball'},
  {category: 'Sporting Goods', price: '$29.99', stocked: false, name: 'Basketball'},
  {category: 'Electronics', price: '$99.99', stocked: true, name: 'iPod Touch'},
  {category: 'Electronics', price: '$399.99', stocked: false, name: 'iPhone 5'},
  {category: 'Electronics', price: '$199.99', stocked: true, name: 'Nexus 7'}
];
